### PR TITLE
[RFC] Implement action "delete"

### PR DESCRIPTION
**Pull request by richardhj**
## Description

Depends on sister contao-community-alliance/dc-general-contao-frontend#6.

## Checklist
- [x] Read and understood the [CONTRIBUTING guidelines](CONTRIBUTING.md)
- [ ] Created tests, if possible
- [ ] All tests passing
- [x] Extended the README / documentation, if necessary
- [x] Added myself to the `@authors` in touched PHP files
- [ ] Checked the changes with phpcq and introduced no new issues

### CODE REVIEW

**Comment by zonky2** [comment]
@richardhj delete works fine - but the action link is like 
```http://localhost:4001/vhosts/contao-3.5.x-fee/metamodels/mitarbeiterliste-edit-login.html?act=delete&id=mm_mitarbeiterliste::93``` but the URL of listing is ```http://localhost:4001/vhosts/contao-3.5.x-fee/metamodels/mitarbeiterliste-mein-erstes-metamodel-v2.html```... after delete we see the edit page instead of listing page

... pls update the UnitTest

**Comment by richardhj** [comment]
Tricky, how do I get the page of the list, when on the editor?
Adding a page picker on the editor for this purpose feels wrong.

I wonder, if we should add the request token to the url
like `http://localhost/edit.html?act=delete&id=mm_mitarbeiterliste::93&rt=122356`.
By doing so, the delete link cannot be shared to a user who is authenticated and deletes the item without noticing.

**Comment by zonky2** [comment]
is the link to the editor absolutely necessary? Can't the call be made directly in the list page?

**Comment by richardhj** [comment]
> is the link to the editor absolutely necessary? Can't the call be made directly in the list page?

Only within the editor module we have the dc-general instance and therefore here we delete the item via DCG.
Within the list module we indeed have a MetaModel instance and could call `$metaModel->delete($item)` — But this is inconsistent as the `copy`, `edit` etc. actions use the DCG (and call the DCG events accordingly).

**Comment by zonky2** [comment]
may be we could automatically return to the list view from the edit page of delete...

**Comment by richardhj** [comment]
Implemented in MetaModels 2.1.

**Pull request closed without merging**
